### ISSUE TITLE
Unable to find or inflate vectors

### ISSUE THREAD

**Issue by RamenSea** [a-student/BetterVectorDrawable#15]
Hey thanks for this Compat library, however I am getting an error when I try to use the vector assets as drawables outside of an XML file.

I am using 0.8 of the BetterVectorDrawable library
generatedDensities = []
version 23.1.1 of appcompat-v7
Compiling with SDK-23
Running on a 4.4.4 Moto G 1st gen

If I don't specifically try to use a drawable I get this in the log

02-03 12:56:11.322 21317-21317/? I/dalvikvm: Could not find method android.content.res.Resources.getDrawable, referenced from method com.bettervectordrawable.VectorDrawableCompat.inflate
02-03 12:56:11.322 21317-21317/? W/dalvikvm: VFY: unable to resolve virtual method 493: Landroid/content/res/Resources;.getDrawable (ILandroid/content/res/Resources$Theme;)Landroid/graphics/drawable/Drawable;
02-03 12:56:11.322 21317-21317/? D/dalvikvm: VFY: replacing opcode 0x6e at 0x0023
02-03 12:56:11.343 21317-21317/? W/dalvikvm: VFY: unable to find class referenced in signature (Landroid/view/SearchEvent;)
02-03 12:56:11.343 21317-21317/? I/dalvikvm: Could not find method android.view.Window$Callback.onSearchRequested, referenced from method android.support.v7.view.WindowCallbackWrapper.onSearchRequested
02-03 12:56:11.343 21317-21317/? W/dalvikvm: VFY: unable to resolve interface method 16781: Landroid/view/Window$Callback;.onSearchRequested (Landroid/view/SearchEvent;)Z
02-03 12:56:11.343 21317-21317/? D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
02-03 12:56:11.343 21317-21317/? I/dalvikvm: Could not find method android.view.Window$Callback.onWindowStartingActionMode, referenced from method android.support.v7.view.WindowCallbackWrapper.onWindowStartingActionMode
02-03 12:56:11.344 21317-21317/? W/dalvikvm: VFY: unable to resolve interface method 16785: Landroid/view/Window$Callback;.onWindowStartingActionMode (Landroid/view/ActionMode$Callback;I)Landroid/view/ActionMode;
02-03 12:56:11.344 21317-21317/? D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002

**This repeats quite a bit**

02-03 12:56:11.417 21317-21317/? W/ReflectionHelper: Unable to find method PorterDuffColorFilter.setMode
                                                     java.lang.NoSuchMethodException: setMode [class android.graphics.PorterDuff$Mode]
                                                         at java.lang.Class.getConstructorOrMethod(Class.java:472)
                                                         at java.lang.Class.getDeclaredMethod(Class.java:640)
                                                         at com.bettervectordrawable.utils.ReflectionHelper.tryFindMethod(ReflectionHelper.java:20)
                                                         at com.bettervectordrawable.lib.graphics.drawable.DrawableExtension.<clinit>(DrawableExtension.java:23)
                                                         at com.bettervectordrawable.lib.graphics.drawable.VectorDrawable$VectorDrawableState.<init>(VectorDrawable.java:697)
                                                         at com.bettervectordrawable.lib.graphics.drawable.VectorDrawable.<init>(VectorDrawable.java:233)
                                                         at com.bettervectordrawable.lib.graphics.drawable.VectorDrawable.<init>(VectorDrawable.java:229)
                                                         at com.bettervectordrawable.lib.graphics.drawable.VectorDrawable.create(VectorDrawable.java:497)
                                                         at com.bettervectordrawable.VectorDrawableCompat.inflate(VectorDrawableCompat.java:115)
                                                         at com.bettervectordrawable.VectorDrawableFactory.get(VectorDrawableFactory.java:36)
                                                         at com.bettervectordrawable.LongSparseArrayDrawableConstantStateWrapper.get(LongSparseArrayDrawableConstantStateWrapper.java:31)
                                                         at com.bettervectordrawable.LongSparseArrayDrawableConstantStateWrapper.get(LongSparseArrayDrawableConstantStateWrapper.java:22)
                                                         at com.bettervectordrawable.LongSparseArrayDrawableConstantStateWrapper.get(LongSparseArrayDrawableConstantStateWrapper.java:10)
                                                         at android.content.res.Resources.loadDrawable(Resources.java:2060)
                                                         at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
                                                         at android.view.View.<init>(View.java:3572)
                                                         at android.widget.TextView.<init>(TextView.java:623)
                                                         at android.widget.Button.<init>(Button.java:107)
                                                         at android.widget.Button.<init>(Button.java:103)
                                                         at basewidgets.FontButton.<init>(FontButton.java:18)
                                                         at java.lang.reflect.Constructor.constructNative(Native Method)
                                                         at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                         at android.view.LayoutInflater.createView(LayoutInflater.java:594)
                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                         at com.myclass.myfragment.onCreateView(myfragment.kt:47)
                                                         at android.app.Fragment.performCreateView(Fragment.java:1700)
                                                         at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890)
                                                         at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
                                                         at android.app.BackStackRecord.run(BackStackRecord.java:684)
                                                         at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1447)
                                                         at android.app.Activity.performStart(Activity.java:5257)
                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2171)
                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2257)
                                                         at android.app.ActivityThread.access$800(ActivityThread.java:139)
                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210)
                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                         at android.os.Looper.loop(Looper.java:136)
                                                         at android.app.ActivityThread.main(ActivityThread.java:5086)
                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                         at java.lang.reflect.Method.invoke(Method.java:515)
                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                         at dalvik.system.NativeStart.main(Native Method)
02-03 12:56:11.418 21317-21317/? I/dalvikvm: Could not find method android.content.res.TypedArray.getChangingConfigurations, referenced from method com.bettervectordrawable.lib.content.res.TypedArrayExtension.getChangingConfigurations
02-03 12:56:11.418 21317-21317/? W/dalvikvm: VFY: unable to resolve virtual method 530: Landroid/content/res/TypedArray;.getChangingConfigurations ()I
02-03 12:56:11.418 21317-21317/? D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006

**Comment by RamenSea** [comment]
If I attempt to get a drawable I get the error:

java.lang.NoSuchMethodError: android.content.res.Resources.getDrawable

**Comment by RamenSea** [comment]
Everything works fine on 5.0+, as I don't activate the library at all. I can't pinpoint the error at all. If theres anything else I could provide please let me know.

Thank you.

**Comment by a-student** [comment]
Hi,
These are warnings, just ignore them.

**Comment by a-student** [comment]
> If I attempt to get a drawable I get the error:
> java.lang.NoSuchMethodError: android.content.res.Resources.getDrawable

Could you please provide a code sample which leads to the error?

**Comment by RamenSea** [comment]
Sorry it took me so long to get back to you. The error resulted when I would get the drawable dynamically. This was done after `VectorDrawableCompat.enableResourceInterceptionFor(...)` set up method

`getContext.getResources.getDrawable(R.drawable.plus_button_active,null)`

However It appears like they have officially brought vector support to the support libraries! http://android-developers.blogspot.com/2016/02/android-support-library-232.html

Thank you greatly for providing this library. :) I look forward to and am using your SVG > Android Vector Tool
